// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status.proto

package status

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求返回状态，success对应http状态码200, InternalError对应http状态码500
type NewResponseStatus struct {
	// 状态码,
	// 1. Success
	// 2. InternalError
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// 信息(展示给用户看的信息)
	// 1. Success
	// 2. An unknown error occurred while processing your request.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 详细信息(开发人员查看的信息)
	Detail               string   `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewResponseStatus) Reset()         { *m = NewResponseStatus{} }
func (m *NewResponseStatus) String() string { return proto.CompactTextString(m) }
func (*NewResponseStatus) ProtoMessage()    {}
func (*NewResponseStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfe4fce6682daf5b, []int{0}
}

func (m *NewResponseStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewResponseStatus.Unmarshal(m, b)
}
func (m *NewResponseStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewResponseStatus.Marshal(b, m, deterministic)
}
func (m *NewResponseStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewResponseStatus.Merge(m, src)
}
func (m *NewResponseStatus) XXX_Size() int {
	return xxx_messageInfo_NewResponseStatus.Size(m)
}
func (m *NewResponseStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NewResponseStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NewResponseStatus proto.InternalMessageInfo

func (m *NewResponseStatus) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *NewResponseStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NewResponseStatus) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

// 通用的响应内容，可以作为删除、更新和错误的响应内容
type NewResponse struct {
	// 一个 API 请求的唯一标识
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// 返回的请求状态
	Status               *NewResponseStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NewResponse) Reset()         { *m = NewResponse{} }
func (m *NewResponse) String() string { return proto.CompactTextString(m) }
func (*NewResponse) ProtoMessage()    {}
func (*NewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfe4fce6682daf5b, []int{1}
}

func (m *NewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewResponse.Unmarshal(m, b)
}
func (m *NewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewResponse.Marshal(b, m, deterministic)
}
func (m *NewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewResponse.Merge(m, src)
}
func (m *NewResponse) XXX_Size() int {
	return xxx_messageInfo_NewResponse.Size(m)
}
func (m *NewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewResponse proto.InternalMessageInfo

func (m *NewResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *NewResponse) GetStatus() *NewResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*NewResponseStatus)(nil), "status.NewResponseStatus")
	proto.RegisterType((*NewResponse)(nil), "status.NewResponse")
}

func init() { proto.RegisterFile("status.proto", fileDescriptor_dfe4fce6682daf5b) }

var fileDescriptor_dfe4fce6682daf5b = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x31, 0x4b, 0xc5, 0x30,
	0x14, 0x85, 0xa9, 0x4a, 0xa5, 0xb7, 0x2e, 0x66, 0x90, 0x08, 0x0e, 0xd2, 0xc9, 0x29, 0xa1, 0xf6,
	0x1f, 0xb8, 0xb9, 0x38, 0xd4, 0x49, 0x07, 0x21, 0x4d, 0x2e, 0xa5, 0x50, 0x93, 0x9a, 0x7b, 0x83,
	0xf8, 0xef, 0x85, 0x34, 0x8f, 0xf7, 0xe0, 0x6d, 0x39, 0x5f, 0x0e, 0x87, 0xef, 0xc2, 0x0d, 0xb1,
	0xe1, 0x44, 0x6a, 0x8b, 0x81, 0x83, 0xa8, 0xf7, 0xd4, 0x7d, 0xc0, 0xed, 0x1b, 0xfe, 0x8e, 0x48,
	0x5b, 0xf0, 0x84, 0xef, 0x19, 0x0a, 0x01, 0x57, 0x36, 0x38, 0x94, 0xd5, 0x63, 0xf5, 0xd4, 0x8c,
	0xf9, 0x2d, 0x24, 0x5c, 0x7f, 0x23, 0x91, 0x99, 0x51, 0x5e, 0x64, 0x7c, 0x88, 0xe2, 0x0e, 0x6a,
	0x87, 0x6c, 0x96, 0x55, 0x5e, 0xe6, 0x8f, 0x92, 0xba, 0x2f, 0x68, 0x4f, 0xa6, 0xc5, 0x03, 0x34,
	0x11, 0x7f, 0x12, 0x12, 0xbf, 0xba, 0xb2, 0x7c, 0x04, 0xa2, 0x87, 0x62, 0x94, 0xd7, 0xdb, 0xe7,
	0x7b, 0x55, 0x74, 0xcf, 0xec, 0xc6, 0x52, 0x7c, 0x19, 0x3e, 0xfb, 0x79, 0xe1, 0xd5, 0x4c, 0xca,
	0xf2, 0x5f, 0xf2, 0xd6, 0x79, 0x65, 0xbd, 0x8e, 0x36, 0xea, 0xbd, 0xa0, 0xf3, 0xa5, 0xa4, 0xe7,
	0x10, 0x12, 0x17, 0x36, 0xd5, 0x19, 0x0e, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x66, 0xd9, 0xd7,
	0x6c, 0x0e, 0x01, 0x00, 0x00,
}
